### PR TITLE
ci: add lint workflow

### PR DESCRIPTION
**Pull request by JamieMagee**

### CODE REVIEW

**Comment by JamieMagee** [comment]
Huh, I expected that action run to show some warnings. I see warnings locally when running PSScriptAnalyze. Maybe I missed some configuration :thinking:

**Comment by jessehouwing** [comment]
That's running on a runner for ya... Let's see what's up.

**Comment by jessehouwing** [comment]
Added pssciptanalyzer and the results are uploaded here:

https://github.com/renovatebot/azure-devops-marketplace/security/code-scanning

**Comment by jessehouwing** [comment]
I'll fix what it spat out so far. Nothing shocking luckily.

**Pull request closed without merging**
